name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          auto-activate-base: false
          use-only-tar-bz2: true  # important for caching

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/.conda/pkgs  # default package cache path
          key: conda-pkgs-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-pkgs-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install dependencies from environment.yml
        run: conda env update --file environment.yml --name base

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') --output=lint.txt || true
