name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          auto-activate-base: false

      - name: Install dependencies including PyMOL
        run: |
          conda install -y -c conda-forge pymol-open-source python=3.11
          pip install pylint
          pip install pandas biopython modal numpy colabfold boto3 dnachisel

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
